### ISSUE TITLE
APP_NAME appears to be ignored

### ISSUE THREAD

**Issue by ralyodio** [guillaumebriday/lobsters-docker#4]
`-e APP_NAME Defaults to "Fullstack News". This should be your application name.`

When I boot up the app with docker-compose up, I still am seeing "Example News" instead of my site name.

**Comment by guillaumebriday** [comment]
Hum, ok can you show me your docker-compose file ?

This is the config I use in production and it works fine: https://github.com/guillaumebriday/selfhosted-services/blob/master/roles/lobsters/tasks/main.yml

**Comment by ralyodio** [comment]
I got it working with this repo

https://github.com/utensils/docker-lobsters

**Comment by guillaumebriday** [comment]
Ok !

I need to see your configuration to help you with my lobsters image 

Can you show me ?

**Comment by guillaumebriday** [comment]
I tried and it works fine,

My docker-compose: 

```yml
  lobsters:
    build: .
    image: guillaumebriday/lobsters-docker
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - APP_NAME=chovy
    ports:
      - "3000:3000"
    depends_on:
      - lobsters-db
```

The result:
<img width="973" alt="Screenshot 2019-08-13 at 00 11 12" src="https://user-images.githubusercontent.com/8252238/62902147-f9617500-bd5e-11e9-8711-006f0d49be4a.png">
